### ISSUE TITLE
Can't open browser on Linux or Mac

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/GitPullRequest#13]
I'm using the Windows trick of `Process.Start("https://github.com/.....")` top open a PR using the default browser. Unfortunately this doesn't work on Lunux and fails with the following:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
```

@bradwilson Do you know what the best way to open a browser on Linux would be? Maybe I should simply output the pull request URL so that people can copy/paste?

**Comment by bradwilson** [comment]
xdg-open: https://linux.die.net/man/1/xdg-open

**Comment by jcansdale** [comment]
@bradwilson do you think it makes sense to execute this as the default action (for `git pr` or `git pr 777`) or do you think I should be using an explicit switch (e.g. `git pr --browse`)?

**Comment by bradwilson** [comment]
I would do this by default.

**Comment by jcansdale** [comment]
It looks like this is already supported.
https://github.com/PowerShell/PowerShell/pull/7198

I think it was throwing for me because I didn't have `xdg-open` installed on my Bash for Windows.
