### ISSUE TITLE
Fetching remote branches for Azure DevOps pull requests

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/GitPullRequest#19]
We need fetch all pull request `pull/*/merge` references for Azure DevOps repos in order to calculate the pull request HEAD and match it with a remote branch HEAD. See:

https://github.com/jcansdale/GitPullRequest/blob/c3e1b59b03c0d16698fcae2bbe54e3d4dc7f3715/GitPullRequest.Services/AzureDevOpsRepository.cs#L29-L30

The current implementation fetches these references and places them under `refs/remotes/{remoteName}/pull/*/merge`. A potential downside of this is that these references show up as remote branches called `{remoteName}/pull/*/merge`. If the user does a `git branch --remotes` or `git branch --all`, these references will show up as remote branches. Depending on how active the repository is, this could be a lot of extra branches and noise!

I was wondering if it might make sense to place these references under their own namespace (something other than `remotes` or `heads`). For example, we could instead place them under: `pulls/{remoteName}/pull/*/merge`. That way they wouldn't clutter the user's repository if they do a `git branch -r`, they would need to do a `git for-each-ref` for them to appear.

What are your thoughts @davidwengier?

**Comment by davidwengier** [comment]
This is a great idea, and after playing with the new release a bit this morning will hopefully solve the other problem of these PR branches showing up when doing `git pr --all`.

**Comment by jcansdale** [comment]
I think there might be an optimization we could do that would avoid the fetch if the pull request/target branches haven't changed.

It would go something like this:
```cs
protected override IDictionary<string, string> GetReferences(IRepository repo, string remoteName)
{
    // for Azure DevOps we need to fetch PR branches so we can explore their history and get the commit before the automatic merge commit that is done on the server
    var remoteRefs = base.GetReferences(repo, remoteName);
    var equal = CompareCommitShas(remoteRefs, repo.Refs);
    if (!equal)
    {
        GitService.Fetch(repo, remoteName, $"+refs/pull/*/merge:refs/remotes/{remoteName}/pull/*/merge");
    }

    return remoteRefs;
}
```

Does that make sense?

**Comment by davidwengier** [comment]
That could work. I didn't bother with any kind of optimisation because I assumed git itself would be doing something similar when doing the fetch.
