### ISSUE TITLE
Allow repository to dictate whether to use shell option

### ISSUE THREAD

**Issue by davidwengier** [jcansdale/GitPullRequest#22]
Doing some playing around today, the only way I could clone a repo from `dev.azure.com` was by using a URL in the form of `https://<organization>@dev.azure.com/<organization>/<project>/_git/<repo>`. Obviously this doesn't work with `git pr` because of the @ sign. It does work fine if use the `--shell` option though.

It would take some refactoring, but if the remote repository could control which git service was used then this could be automatic in these scenarios, whilst still remain opt-in for others.

**Comment by jcansdale** [comment]
We could easily make this method responsible for choosing the `IGitService` implementation:

https://github.com/jcansdale/GitPullRequest/blob/e7c568c74bc7c946a4be3a344bb232b1990957ff/GitPullRequest.Services/GitRepositoryFactory.cs#L8-L25

Maybe change the signature to:
```
RemoteRepository Create(IRepository repo, string remoteName, IGitService gitService = null)
```

Where `gitService = null` delegates to this method or the caller can pass in a specific implementation (e.g. when user specifies `--shell` or for unit testing).
