### ISSUE TITLE
Help option not working in Git Bash

### ISSUE THREAD

**Issue by drewnoakes** [jcansdale/GitPullRequest#43]
![image](https://user-images.githubusercontent.com/350947/51272322-c0784200-19c1-11e9-860e-6d5479d9984f.png)

**Comment by drewnoakes** [comment]
I see from the code the help option's supposed to be `-?`.

![image](https://user-images.githubusercontent.com/350947/51272440-01705680-19c2-11e9-9154-04ebbcaa9308.png)

**Comment by jcansdale** [comment]
Hey 👋,

I'm not sure it's possible to override the `--help` option for this kind of Git extension. When git can't find a built in command called `pr`, it tries executing the `git-pr` application instead. I don't know if there' any such mechanism when using `--help`?

**Comment by drewnoakes** [comment]
I took a look around and am not sure it's possible. `git foo --help` is converted to `git help foo`, and I don't see a way to do this from the man page for `git help`:

https://git-scm.com/docs/git-help

Will close this.

**Comment by jcansdale** [comment]
Thanks for looking into this! It's 360 review time and I so nearly got nerd-sniped. 😉
